### ISSUE TITLE
Make multiset more libstd like

### ISSUE THREAD

**Issue by mashedcode** [jmitchell/multiset#13]
Please leave a short note on where we're standing with this idea and these PRs so that I know how to move on. #6 #7 #8 #10 #11 #12

**Comment by jmitchell** [comment]
I'm generally in favor of that strategy. Thanks for all your contributions!

Still open:
* #10 (Eq implementation): awaiting minor optimization now that `len()` is available
* #11 (Eq test): waiting on #10. If it's easier, feel free to close #10 since #11 has those changes.
* #8 (Use references instead of values): blocked on https://github.com/jmitchell/multiset/pull/8#discussion_r159162969

**Comment by mashedcode** [comment]
Thank you so much! #10 and #11 are now merged.

**Comment by jmitchell** [comment]
#8 has been merged as well.

Closing the issue for now.
